macro(smtg_print_generator_copyright_header)
    message("")
    message("==================================================")
    message("")
    message(" Steinberg Media Technologies GmbH")
    message(" VST3 plug-in generator")
    message("")
    message("==================================================")
    message("")
endmacro(smtg_print_generator_copyright_header)
